## PyEcharts天猫数据可视化项目

### 订单数据分析

本数据集共收集了发生在一个月内的28010条数据，包含以下：
- 订单编号
- 总金额
- 买家实际支付金额: 总金额-退款金额
- 收货地址： 各个省份
- 订单创建时间
- 订单付款时间
- 退款金额： 付款后申请退款的金额。如无付过款，退款金额为0

#### 读取数据

In [1]:
import pandas as pd

from pyecharts import options as opts
from pyecharts.charts import Map, Timeline, Bar, Line, Pie

In [2]:
data = pd.read_csv('tmall_order_report.csv')
data.head()

,订单编号,总金额,买家实际支付金额,收货地址,订单创建时间,订单付款时间,退款金额
0,1,178.8,0.0,上海,2022-03-21 00:00:00,NaN,0.0
1,2,21.0,21.0,内蒙古自治区,2022-03-20 23:59:54,2022-03-21 00:00:02,0.0
2,3,37.0,0.0,安徽省,2022-03-20 23:59:35,NaN,0.0
3,4,157.0,157.0,湖南省,2022-03-20 23:58:34,2022-03-20 23:58:44,0.0
4,5,64.8,0.0,江苏省,2022-03-20 23:57:04,2022-03-20 23:57:11,64.8

In [3]:
data.shape

# 28010行 7列

(28010, 7)

#### 数据处理

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28010 entries, 0 to 28009
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   订单编号      28010 non-null  int64
 1   总金额       28010 non-null  float64
 2   买家实际支付金额  28010 non-null  float64
 3   收货地址      28010 non-null  object
 4   订单创建时间    28010 non-null  object
 5   订单付款时间    24087 non-null  object
 6   退款金额      28010 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.5+ MB

In [5]:
data.columns

Index(['订单编号', '总金额', '买家实际支付金额', '收货地址 ', '订单创建时间', '订单付款时间 ', '退款金额'], dtype='object')

In [6]:
# 去除列名中的空格
data.columns = data.columns.str.strip()

In [7]:
data.columns

Index(['订单编号', '总金额', '买家实际支付金额', '收货地址', '订单创建时间', '订单付款时间', '退款金额'], dtype='object')

#### 重复值查看

In [8]:
data.duplicated().sum()

# 没有重复值

0

#### 缺失值查看

In [9]:
# data.info()

data.isnull().sum()
#  订单付款时间   有3923空

订单编号           0
总金额            0
买家实际支付金额       0
收货地址           0
订单创建时间         0
订单付款时间      3923
退款金额           0
dtype: int64

### PyEcharts数据可视化

In [10]:
data.head()

,订单编号,总金额,买家实际支付金额,收货地址,订单创建时间,订单付款时间,退款金额
0,1,178.8,0.0,上海,2022-03-21 00:00:00,NaN,0.0
1,2,21.0,21.0,内蒙古自治区,2022-03-20 23:59:54,2022-03-21 00:00:02,0.0
2,3,37.0,0.0,安徽省,2022-03-20 23:59:35,NaN,0.0
3,4,157.0,157.0,湖南省,2022-03-20 23:58:34,2022-03-20 23:58:44,0.0
4,5,64.8,0.0,江苏省,2022-03-20 23:57:04,2022-03-20 23:57:11,64.8

#### 各省份的订单量

In [11]:
data.收货地址.value_counts()

上海          3353
广东省         2463
江苏省         2126
浙江省         2061
北京          2054
四川省         2019
山东省         1804
辽宁省         1187
天津          1153
湖南省         1099
河北省         1083
重庆          1036
河南省          966
云南省          778
安徽省          609
陕西省          536
福建省          489
山西省          465
广西壮族自治区      436
江西省          411
吉林省          401
黑龙江省         379
贵州省          345
内蒙古自治区       215
海南省          178
甘肃省          167
湖北省           75
新疆维吾尔自治区      58
宁夏回族自治区       42
青海省           19
西藏自治区          3
Name: 收货地址, dtype: int64

In [12]:
def province_map(p):
    if p in ['北京', '天津', '上海', '重庆']:
        return p + '市'
    return p

data.收货地址 = data.收货地址.map(province_map)

In [13]:
data.收货地址.value_counts()

上海市         3353
广东省         2463
江苏省         2126
浙江省         2061
北京市         2054
四川省         2019
山东省         1804
辽宁省         1187
天津市         1153
湖南省         1099
河北省         1083
重庆市         1036
河南省          966
云南省          778
安徽省          609
陕西省          536
福建省          489
山西省          465
广西壮族自治区      436
江西省          411
吉林省          401
黑龙江省         379
贵州省          345
内蒙古自治区       215
海南省          178
甘肃省          167
湖北省           75
新疆维吾尔自治区      58
宁夏回族自治区       42
青海省           19
西藏自治区          3
Name: 收货地址, dtype: int64

In [14]:
# 查看订单付款时间不为空的
data.订单付款时间.notnull()

# 过滤掉（删掉）没有付款的订单数据
data[data.订单付款时间.notnull()]

,订单编号,总金额,买家实际支付金额,收货地址,订单创建时间,订单付款时间,退款金额
1,2,21.0,21.0,内蒙古自治区,2022-03-20 23:59:54,2022-03-21 00:00:02,0.0
3,4,157.0,157.0,湖南省,2022-03-20 23:58:34,2022-03-20 23:58:44,0.0
4,5,64.8,0.0,江苏省,2022-03-20 23:57:04,2022-03-20 23:57:11,64.8
5,6,327.7,148.9,浙江省,2022-03-20 23:56:39,2022-03-20 23:56:53,178.8
6,7,357.0,357.0,天津市,2022-03-20 23:56:36,2022-03-20 23:56:40,0.0
...,...,...,...,...,...,...,...
28002,28003,77.0,77.0,重庆市,2022-03-27 00:02:39,2022-03-27 00:03:27,0.0
28003,28004,157.0,157.0,山东省,2022-03-27 00:01:42,2022-03-27 00:01:47,0.0
28005,28006,37.0,37.0,四川省,2022-03-27 00:01:00,2022-03-27 00:01:10,0.0
28008,28009,37.0,37.0,辽宁省,2022-03-27 00:00:09,2022-03-27 00:00:17,0.0
28009,28010,37.0,37.0,广东省,2022-03-27 00:00:06,2022-03-27 00:00:11,0.0

In [15]:
# 统计各个省份的订单量

result = data[data.订单付款时间.notnull()].groupby('收货地址')[['订单编号']].count()
result

          订单编号
收货地址
上海市       3060
云南省        667
内蒙古自治区     176
北京市       1853
吉林省        336
四川省       1752
天津市       1031
宁夏回族自治区     40
安徽省        528
山东省       1484
山西省        395
广东省       2022
广西壮族自治区    353
新疆维吾尔自治区    43
江苏省       1845
江西省        331
河北省        885
河南省        792
浙江省       1822
海南省        156
湖北省         57
湖南省        935
甘肃省        132
福建省        425
西藏自治区        2
贵州省        286
辽宁省       1012
重庆市        896
陕西省        441
青海省         18
黑龙江省       312

In [16]:
result2 = result.to_dict()['订单编号']
result2

{'上海市': 3060,
 '云南省': 667,
 '内蒙古自治区': 176,
 '北京市': 1853,
 '吉林省': 336,
 '四川省': 1752,
 '天津市': 1031,
 '宁夏回族自治区': 40,
 '安徽省': 528,
 '山东省': 1484,
 '山西省': 395,
 '广东省': 2022,
 '广西壮族自治区': 353,
 '新疆维吾尔自治区': 43,
 '江苏省': 1845,
 '江西省': 331,
 '河北省': 885,
 '河南省': 792,
 '浙江省': 1822,
 '海南省': 156,
 '湖北省': 57,
 '湖南省': 935,
 '甘肃省': 132,
 '福建省': 425,
 '西藏自治区': 2,
 '贵州省': 286,
 '辽宁省': 1012,
 '重庆市': 896,
 '陕西省': 441,
 '青海省': 18,
 '黑龙江省': 312}

In [17]:
result2.items()

dict_items([('上海市', 3060), ('云南省', 667), ('内蒙古自治区', 176), ('北京市', 1853), ('吉林省', 336), ('四川省', 1752), ('天津市', 1031), ('宁夏回族自治区', 40), ('安徽省', 528), ('山东省', 1484), ('山西省', 395), ('广东省', 2022), ('广西壮族自治区', 353), ('新疆维吾尔自治区', 43), ('江苏省', 1845), ('江西省', 331), ('河北省', 885), ('河南省', 792), ('浙江省', 1822), ('海南省', 156), ('湖北省', 57), ('湖南省', 935), ('甘肃省', 132), ('福建省', 425), ('西藏自治区', 2), ('贵州省', 286), ('辽宁省', 1012), ('重庆市', 896), ('陕西省', 441), ('青海省', 18), ('黑龙江省', 312)])

In [18]:
list(result2.items())

[('上海市', 3060),
 ('云南省', 667),
 ('内蒙古自治区', 176),
 ('北京市', 1853),
 ('吉林省', 336),
 ('四川省', 1752),
 ('天津市', 1031),
 ('宁夏回族自治区', 40),
 ('安徽省', 528),
 ('山东省', 1484),
 ('山西省', 395),
 ('广东省', 2022),
 ('广西壮族自治区', 353),
 ('新疆维吾尔自治区', 43),
 ('江苏省', 1845),
 ('江西省', 331),
 ('河北省', 885),
 ('河南省', 792),
 ('浙江省', 1822),
 ('海南省', 156),
 ('湖北省', 57),
 ('湖南省', 935),
 ('甘肃省', 132),
 ('福建省', 425),
 ('西藏自治区', 2),
 ('贵州省', 286),
 ('辽宁省', 1012),
 ('重庆市', 896),
 ('陕西省', 441),
 ('青海省', 18),
 ('黑龙江省', 312)]

In [19]:
[*result2.items()]

[('上海市', 3060),
 ('云南省', 667),
 ('内蒙古自治区', 176),
 ('北京市', 1853),
 ('吉林省', 336),
 ('四川省', 1752),
 ('天津市', 1031),
 ('宁夏回族自治区', 40),
 ('安徽省', 528),
 ('山东省', 1484),
 ('山西省', 395),
 ('广东省', 2022),
 ('广西壮族自治区', 353),
 ('新疆维吾尔自治区', 43),
 ('江苏省', 1845),
 ('江西省', 331),
 ('河北省', 885),
 ('河南省', 792),
 ('浙江省', 1822),
 ('海南省', 156),
 ('湖北省', 57),
 ('湖南省', 935),
 ('甘肃省', 132),
 ('福建省', 425),
 ('西藏自治区', 2),
 ('贵州省', 286),
 ('辽宁省', 1012),
 ('重庆市', 896),
 ('陕西省', 441),
 ('青海省', 18),
 ('黑龙江省', 312)]

In [35]:
c = (
    Map()
    .add('各省份订单量', 
        [*result2.items()], 
         'china',
         is_map_symbol_show=False
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
    .set_global_opts(
        title_opts=opts.TitleOpts(title='各省份订单量'),
        visualmap_opts=opts.VisualMapOpts(max_=2000)
    )
)
c.render_notebook()

#### 时间序列分析

In [21]:
data.head()

,订单编号,总金额,买家实际支付金额,收货地址,订单创建时间,订单付款时间,退款金额
0,1,178.8,0.0,上海市,2022-03-21 00:00:00,NaN,0.0
1,2,21.0,21.0,内蒙古自治区,2022-03-20 23:59:54,2022-03-21 00:00:02,0.0
2,3,37.0,0.0,安徽省,2022-03-20 23:59:35,NaN,0.0
3,4,157.0,157.0,湖南省,2022-03-20 23:58:34,2022-03-20 23:58:44,0.0
4,5,64.8,0.0,江苏省,2022-03-20 23:57:04,2022-03-20 23:57:11,64.8

In [22]:
data.info()

# 订单创建时间和订单付款时间 先修改成时间类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28010 entries, 0 to 28009
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   订单编号      28010 non-null  int64
 1   总金额       28010 non-null  float64
 2   买家实际支付金额  28010 non-null  float64
 3   收货地址      28010 non-null  object
 4   订单创建时间    28010 non-null  object
 5   订单付款时间    24087 non-null  object
 6   退款金额      28010 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.5+ MB

In [23]:
data.订单创建时间 = pd.to_datetime(data.订单创建时间)
data.订单付款时间 = pd.to_datetime(data.订单付款时间)

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28010 entries, 0 to 28009
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   订单编号      28010 non-null  int64
 1   总金额       28010 non-null  float64
 2   买家实际支付金额  28010 non-null  float64
 3   收货地址      28010 non-null  object
 4   订单创建时间    28010 non-null  datetime64[ns]
 5   订单付款时间    24087 non-null  datetime64[ns]
 6   退款金额      28010 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(1)
memory usage: 1.5+ MB

#### 每天订单量统计可视化

In [25]:
data.订单创建时间

0       2022-03-21 00:00:00
1       2022-03-20 23:59:54
2       2022-03-20 23:59:35
3       2022-03-20 23:58:34
4       2022-03-20 23:57:04
                ...
28005   2022-03-27 00:01:00
28006   2022-03-27 00:00:18
28007   2022-03-27 00:00:17
28008   2022-03-27 00:00:09
28009   2022-03-27 00:00:06
Name: 订单创建时间, Length: 28010, dtype: datetime64[ns]

In [26]:
order_add_time = data.订单创建时间.map(lambda x: x.strftime('%Y-%m-%d'))

In [27]:
order_add_time

0        2022-03-21
1        2022-03-20
2        2022-03-20
3        2022-03-20
4        2022-03-20
            ...
28005    2022-03-27
28006    2022-03-27
28007    2022-03-27
28008    2022-03-27
28009    2022-03-27
Name: 订单创建时间, Length: 28010, dtype: object

In [28]:
# 按照订单创建时间 分组，得到每一天的订单量
result3 = data.groupby(order_add_time).agg({'订单编号': 'count'}).to_dict()['订单编号']
result3

{'2022-03-01': 176,
 '2022-03-02': 222,
 '2022-03-03': 267,
 '2022-03-04': 469,
 '2022-03-05': 369,
 '2022-03-06': 144,
 '2022-03-07': 177,
 '2022-03-09': 404,
 '2022-03-10': 27,
 '2022-03-11': 15,
 '2022-03-12': 1,
 '2022-03-13': 5,
 '2022-03-14': 7,
 '2022-03-15': 5,
 '2022-03-17': 390,
 '2022-03-18': 1015,
 '2022-03-19': 1025,
 '2022-03-20': 1345,
 '2022-03-21': 2068,
 '2022-03-22': 2027,
 '2022-03-23': 2200,
 '2022-03-24': 1998,
 '2022-03-25': 3416,
 '2022-03-26': 2849,
 '2022-03-27': 2586,
 '2022-03-28': 2691,
 '2022-03-29': 2112}

In [29]:
list(result3.keys())

['2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-05',
 '2022-03-06',
 '2022-03-07',
 '2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29']

In [30]:
c = (
    Line()
    .add_xaxis(list(result3.keys()))
    .add_yaxis(
        '订单量',
        list(result3.values())
    )
    .set_series_opts(
        label_opts=opts.LabelOpts(is_show=False),
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_='max')
            ]
        )
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title='每天订单量')
    )
)
c.render_notebook()

#### 每小时订单量统计可视化

In [31]:
order_add_time2 = data.订单创建时间.map(lambda x: x.strftime('%H'))

In [32]:
order_add_time2.value_counts()

21    2204
22    2126
20    1990
15    1720
10    1672
23    1644
11    1640
19    1532
14    1500
16    1481
12    1367
13    1339
09    1283
18    1270
17    1205
00    1043
08     880
07     556
01     530
02     341
06     250
03     189
04     135
05     113
Name: 订单创建时间, dtype: int64

In [33]:
result4 = data.groupby(order_add_time2).agg({'订单编号': 'count'}).to_dict()['订单编号']
result4

{'00': 1043,
 '01': 530,
 '02': 341,
 '03': 189,
 '04': 135,
 '05': 113,
 '06': 250,
 '07': 556,
 '08': 880,
 '09': 1283,
 '10': 1672,
 '11': 1640,
 '12': 1367,
 '13': 1339,
 '14': 1500,
 '15': 1720,
 '16': 1481,
 '17': 1205,
 '18': 1270,
 '19': 1532,
 '20': 1990,
 '21': 2204,
 '22': 2126,
 '23': 1644}

In [34]:
c = (
    Bar()
    .add_xaxis( list(result4.keys()) )
    .add_yaxis('订单量', list(result4.values()))
    
    .set_series_opts(
        label_opts=opts.LabelOpts(is_show=False),
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_='max')
            ]
        )
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title='每小时订单量')
    )
)
c.render_notebook()