## PyEcharts双11销售数据可视化

### 销售数据分析

本数据集共收集了27598条数据，包含以下：
- update_time：更新时间
- id: 编号
- title：商品标题
- price：价格 
- sale_count：销售量
- comment_count：评论数量
- 店名： 店铺名称

#### 读取数据

In [1]:
import pandas as pd

from pyecharts import options as opts
from pyecharts.charts import Map, Timeline, Bar, Line, Pie

In [2]:
data = pd.read_csv('double11beautysales.csv')
data.head()

,update_time,id,title,price,sale_count,comment_count,店名
0,2022/11/14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂
1,2022/11/14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂
2,2022/11/14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂
3,2022/11/14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂
4,2022/11/14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂

In [3]:
data.shape

(27598, 7)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27598 entries, 0 to 27597
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   update_time    27598 non-null  object
 1   id             27598 non-null  object
 2   title          27598 non-null  object
 3   price          27598 non-null  float64
 4   sale_count     25244 non-null  float64
 5   comment_count  25244 non-null  float64
 6   店名             27598 non-null  object
dtypes: float64(3), object(4)
memory usage: 1.5+ MB

#### 重复值处理

In [6]:
data.duplicated().sum()

# 86条数据重复了

86

In [7]:
data.drop_duplicates(inplace=True)

In [9]:
# 重置索引
data.reset_index(drop=True, inplace=True)

In [10]:
data.head()

,update_time,id,title,price,sale_count,comment_count,店名
0,2022/11/14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂
1,2022/11/14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂
2,2022/11/14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂
3,2022/11/14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂
4,2022/11/14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂

In [11]:
data.duplicated().sum()

0

#### 缺失值处理

In [12]:
data.isnull().sum()

update_time         0
id                  0
title               0
price               0
sale_count       2350
comment_count    2350
店名                  0
dtype: int64

In [13]:
data.fillna(0, inplace=True)

In [14]:
data.isnull().sum()

update_time      0
id               0
title            0
price            0
sale_count       0
comment_count    0
店名               0
dtype: int64

#### 时间序列分析

In [15]:
data.head()

,update_time,id,title,price,sale_count,comment_count,店名
0,2022/11/14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂
1,2022/11/14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂
2,2022/11/14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂
3,2022/11/14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂
4,2022/11/14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂

In [16]:
pd.to_datetime(data.update_time)

0       2022-11-14
1       2022-11-14
2       2022-11-14
3       2022-11-14
4       2022-11-14
           ...
27507   2022-11-05
27508   2022-11-05
27509   2022-11-05
27510   2022-11-05
27511   2022-11-05
Name: update_time, Length: 27512, dtype: datetime64[ns]

In [17]:
data.update_time = pd.to_datetime(data.update_time).map(lambda x: x.strftime('%Y-%m-%d'))

In [18]:
data.head()

,update_time,id,title,price,sale_count,comment_count,店名
0,2022-11-14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂
1,2022-11-14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂
2,2022-11-14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂
3,2022-11-14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂
4,2022-11-14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂

In [19]:
# 加一列：销售额
data['sale_amount'] = data.price * data.sale_count

In [20]:
data.head()

,update_time,id,title,price,sale_count,comment_count,店名,sale_amount
0,2022-11-14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂,3713941.0
1,2022-11-14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂,1575668.0
2,2022-11-14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂,1254132.0
3,2022-11-14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂,980590.0
4,2022-11-14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂,722244.0

In [23]:
# 按销量排序
# data[data.sale_count > 0].sort_values(by=['sale_count'])

### PyEcharts可视化

#### 每天销售量统计分析

In [25]:
data.head(3)

,update_time,id,title,price,sale_count,comment_count,店名,sale_amount
0,2022-11-14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂,3713941.0
1,2022-11-14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂,1575668.0
2,2022-11-14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂,1254132.0

In [26]:
result = data.groupby('update_time').agg({'sale_count': 'sum'}).to_dict()['sale_count']
result

{'2022-11-05': 32021763.0,
 '2022-11-06': 32617979.0,
 '2022-11-07': 31596576.0,
 '2022-11-08': 32666289.0,
 '2022-11-09': 33323552.0,
 '2022-11-10': 31775729.0,
 '2022-11-11': 27818183.0,
 '2022-11-12': 28821197.0,
 '2022-11-13': 29301688.0,
 '2022-11-14': 29953666.0}

In [32]:
c = (
    Line()
    .add_xaxis( list(result.keys()) )
    .add_yaxis('销量', list(result.values()))
    
    .set_global_opts(
        title_opts=opts.TitleOpts(title='每天的销售量')
    )
    .set_series_opts(
        areastyle_opts=opts.AreaStyleOpts(opacity=0.5),
        label_opts=opts.LabelOpts(is_show=False),
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_='max', name='最大值'),
                opts.MarkPointItem(type_='min', name='最小值'),
            ]
        )
    )
    
)
c.render_notebook()

#### 时间升序

In [35]:
times = list( data.update_time.unique() )
times.reverse()
times

['2022-11-05',
 '2022-11-06',
 '2022-11-07',
 '2022-11-08',
 '2022-11-09',
 '2022-11-10',
 '2022-11-11',
 '2022-11-12',
 '2022-11-13',
 '2022-11-14']

In [38]:
data.head(2)

,update_time,id,title,price,sale_count,comment_count,店名,sale_amount
0,2022-11-14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂,3713941.0
1,2022-11-14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂,1575668.0

In [37]:
data.店名.unique()

array(['自然堂', '资生堂', '植村秀', '悦诗风吟', '玉兰油', '雅漾', '雅诗兰黛', '雪花秀', '相宜本草',
       '薇姿', '倩碧', '欧珀莱', '欧莱雅', '妮维雅', '蜜丝佛陀', '美加净', '美宝莲', '兰芝', '兰蔻',
       '娇兰', '佰草集', 'SKII'], dtype=object)

In [55]:
# 时间轮播图

tl = Timeline()

tl.add_schema(
    is_auto_play=True,  # 是否自动播放
    is_loop_play=True,  # 是否循环播放
    play_interval=2000  # 每隔2秒动一次
)

for dt in times:
    item = data[data.update_time <= dt].groupby('店名') \
            .agg({'sale_count': 'sum', 'sale_amount': 'sum'}) \
            .sort_values(by='sale_count', ascending=False)[:10]  \
            .sort_values(by='sale_count')  \
            .to_dict()
    # print(item)
    
    # 柱形图
    bar = (
        Bar()
        .add_xaxis(list(item['sale_count'].keys()))
        .add_yaxis('销售量',
                  [round(val/1000000,1) for val in item['sale_count'].values()],
                   label_opts=opts.LabelOpts(position='right', 
                                            formatter='{@[1]/}百万件'
                                            )
        )
         .add_yaxis('销售额',
                  [round(val/100000000,1) for val in item['sale_amount'].values()],
                   label_opts=opts.LabelOpts(position='right', 
                                            formatter='{@[1]/}亿元'
                                            )
        )
        
        .reversal_axis()  # 条形图
        .set_global_opts(
            title_opts=opts.TitleOpts(title='累计销售量Top10')
        )
    )
    tl.add(bar, dt)

In [58]:
item = data.groupby('店名') \
            .agg({'sale_count': 'sum'}) \
            .sort_values(by='sale_count', ascending=False)[:10]  \
            .to_dict()['sale_count']

item = {k: round(v/10000, 1)  for k, v in item.items()}
item
# 单位是：万

{'相宜本草': 6546.3,
 '美宝莲': 3935.8,
 '悦诗风吟': 3907.0,
 '妮维雅': 3825.5,
 '欧莱雅': 3377.3,
 '自然堂': 1783.7,
 '蜜丝佛陀': 1539.1,
 '佰草集': 1499.4,
 '兰芝': 913.0,
 '美加净': 882.6}

In [60]:
c = (
    Pie()
    .add(
        '销售量',
        list(item.items())
    )
    .set_series_opts(
        label_opts=opts.LabelOpts(formatter="{b}: {c}w({d})%")
    )
)
c.render_notebook()

#### 价格排序

In [61]:
data.head()

,update_time,id,title,price,sale_count,comment_count,店名,sale_amount
0,2022-11-14,A18164178225,CHANDO/自然堂 雪域精粹纯粹滋润霜50g 补水保湿 滋润水润面霜,139.0,26719.0,2704.0,自然堂,3713941.0
1,2022-11-14,A18177105952,CHANDO/自然堂凝时鲜颜肌活乳液120ML 淡化细纹补水滋润专柜正品,194.0,8122.0,1492.0,自然堂,1575668.0
2,2022-11-14,A18177226992,CHANDO/自然堂活泉保湿修护精华水（滋润型135ml 补水控油爽肤水,99.0,12668.0,589.0,自然堂,1254132.0
3,2022-11-14,A18178033846,CHANDO/自然堂 男士劲爽控油洁面膏 100g 深层清洁 男士洗面奶,38.0,25805.0,4287.0,自然堂,980590.0
4,2022-11-14,A18178045259,CHANDO/自然堂雪域精粹纯粹滋润霜（清爽型）50g补水保湿滋润霜,139.0,5196.0,618.0,自然堂,722244.0

In [66]:
item = data.groupby('店名') \
            .agg({'price': 'mean'}) \
            .sort_values(by='price', ascending=True)[:20]  \
            .to_dict()['price']

item

{'美加净': 44.69461859356377,
 '妮维雅': 73.78905311778291,
 '悦诗风吟': 121.24594505130752,
 '相宜本草': 122.95844630616908,
 '蜜丝佛陀': 142.11889400921658,
 '美宝莲': 148.75757575757575,
 '欧莱雅': 167.2826982492276,
 '自然堂': 180.13021276595745,
 '雅漾': 212.6184012066365,
 '欧珀莱': 276.21854304635764,
 '薇姿': 281.0857908847185,
 '佰草集': 289.8231713780919,
 '植村秀': 311.7866666666667,
 '玉兰油': 329.65729442970826,
 '倩碧': 346.0921902524956,
 '兰芝': 356.6158088235294,
 '资生堂': 577.4384896467723,
 '兰蔻': 756.4007782101168,
 '雅诗兰黛': 872.4707182320442,
 '雪花秀': 901.0828729281768}

In [67]:
c = (
    Bar()
    .add_xaxis(list(item.keys()))
    .add_yaxis(
        '价格',
        [round(v, 2)  for v in item.values()],
        label_opts=opts.LabelOpts(position='right')
    )
    .reversal_axis()
    
    .set_global_opts(title_opts=opts.TitleOpts(title='平均价格Top20'))
)
c.render_notebook()